name: deploy
on:
  workflow_dispatch:
jobs:
  deploy:
    runs-on: [self-hosted, Linux, X64, jammy, large]
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Run demo.bash
        run: bash demo.bash